# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstDraft.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.






import sys
from PyQt5.QtWidgets import QApplication, QWidget, QComboBox, QPushButton, QVBoxLayout
from PyQt5.QtCore import Qt

class CheckableComboBox(QComboBox):
	def __init__(self, frame):
		super().__init__(frame)
		self._changed = False

		self.view().pressed.connect(self.handleItemPressed)

	def setItemChecked(self, index, checked=False):
		item = self.model().item(index, self.modelColumn()) # QStandardItem object

		if checked:
			item.setCheckState(Qt.Checked)
		else:
			item.setCheckState(Qt.Unchecked)

	def handleItemPressed(self, index):
		item = self.model().itemFromIndex(index)

		if item.checkState() == Qt.Checked:
			item.setCheckState(Qt.Unchecked)
		else:
			item.setCheckState(Qt.Checked)
		self._changed = True


	def hidePopup(self):
		if not self._changed:
			super().hidePopup()
		self._changed = False

	def itemChecked(self, index):
		item = self.model().item(index, self.modelColumn())
		return item.checkState() == Qt.Checked













from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1052, 686)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(180, 50, 751, 511))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(280, 20, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.attrSelectcomboBox1 = QtWidgets.QComboBox(self.frame)
        self.attrSelectcomboBox1.setGeometry(QtCore.QRect(420, 280, 221, 31))
        self.attrSelectcomboBox1.setObjectName("attrSelectcomboBox1")
        self.attrSelectcomboBox1.addItem("")
        self.attrSelectcomboBox1.addItem("")
        self.attrSelectcomboBox1.addItem("")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(60, 70, 611, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(60, 160, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(60, 280, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.logSelectcomboBox1 = QtWidgets.QComboBox(self.frame)
        self.logSelectcomboBox1.setGeometry(QtCore.QRect(420, 160, 221, 31))
        self.logSelectcomboBox1.setObjectName("logSelectcomboBox1")
        self.logSelectcomboBox1.addItem("")
        self.logSelectcomboBox1.addItem("")
        self.logSelectcomboBox1.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(80, 430, 231, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.addToLogs)

        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 430, 231, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setEnabled(True)
        self.label_5.setGeometry(QtCore.QRect(60, 210, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.logSelectcomboBox2 = QtWidgets.QComboBox(self.frame)
        self.logSelectcomboBox2.setGeometry(QtCore.QRect(420, 210, 221, 31))
        self.logSelectcomboBox2.setObjectName("logSelectcomboBox2")
        self.logSelectcomboBox2.addItem("")
        self.logSelectcomboBox2.addItem("")
        self.logSelectcomboBox2.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1052, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)


        self.checkableComboBox1 = CheckableComboBox(self.frame)
        self.checkableComboBox1.setGeometry(QtCore.QRect(420, 210, 221, 31))
        self.checkableComboBox1.setObjectName("checkableComboBox1")

        for i in range(6):
            self.checkableComboBox1.addItem('Item {0}'.format(str(i)))
            self.checkableComboBox1.setItemChecked(i, False)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Match Miner"))
        self.attrSelectcomboBox1.setItemText(0, _translate("MainWindow", "attribute1"))
        self.attrSelectcomboBox1.setItemText(1, _translate("MainWindow", "attribute2"))
        self.attrSelectcomboBox1.setItemText(2, _translate("MainWindow", "attribute3"))
        self.label_2.setText(_translate("MainWindow", "Merge events across logs based on matching attribute(s)."))
        self.label_3.setText(_translate("MainWindow", "Select first event log:"))
        self.label_4.setText(_translate("MainWindow", "Select attribute(s) to match on:"))
        self.logSelectcomboBox1.setItemText(0, _translate("MainWindow", "log1"))
        self.logSelectcomboBox1.setItemText(1, _translate("MainWindow", "log2"))
        self.logSelectcomboBox1.setItemText(2, _translate("MainWindow", "log3"))
        self.pushButton.setText(_translate("MainWindow", "Add to event logs"))
        self.pushButton_2.setText(_translate("MainWindow", "Export"))
        self.label_5.setText(_translate("MainWindow", "Select second event log:"))
        self.logSelectcomboBox2.setItemText(0, _translate("MainWindow", "log1"))
        self.logSelectcomboBox2.setItemText(1, _translate("MainWindow", "log2"))
        self.logSelectcomboBox2.setItemText(2, _translate("MainWindow", "log3"))

    def addToLogs(self):
        manualMiner(self.logSelectcomboBox1.currentText(), self.logSelectcomboBox2.currentText(), [], self.attrSelectcomboBox1.currentText())


def manualMiner(log1, log2, obj_relation, attribute):
    print(log1 + " " + log2 + ": " + attribute)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())



