# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stackedWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 386, 536))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setGeometry(QtCore.QRect(60, 190, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 290, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")


        self.operatorFrame = QtWidgets.QFrame(self.page_2)
    #    self.rightGridLayout.addWidget(self.operatorFrame, 0, 0, 1, 2)

    #    self.operatorFrame.setGeometry(QtCore.QRect(20, 20, 751, 511))
        self.operatorFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.operatorFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.operatorFrame.setObjectName("operatorFrame")

        # set inner layout of right area
        self.innerRightLayout = QtWidgets.QGridLayout(self.operatorFrame)
        self.innerRightLayout.setObjectName("innerRightLayout")

        self.operatorTitleLabel = QtWidgets.QLabel(self.operatorFrame)
    #    self.operatorTitleLabel.setGeometry(QtCore.QRect(280, 20, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.operatorTitleLabel.setFont(font)
        self.operatorTitleLabel.setObjectName("operatorTitleLabel")

        self.operatorDescriptionLabel = QtWidgets.QLabel(self.operatorFrame)
        self.operatorDescriptionLabel.setEnabled(True)
    #    self.operatorDescriptionLabel.setGeometry(QtCore.QRect(60, 70, 611, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.operatorDescriptionLabel.setFont(font)
        self.operatorDescriptionLabel.setObjectName("operatorDescriptionLabel")
        self.operatorSelectorLabel_1 = QtWidgets.QLabel(self.operatorFrame)
        self.operatorSelectorLabel_1.setEnabled(True)
    #    self.operatorSelectorLabel_1.setGeometry(QtCore.QRect(60, 160, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.operatorSelectorLabel_1.setFont(font)
        self.operatorSelectorLabel_1.setObjectName("operatorSelectorLabel_1")
        self.operatorSelectorLabel_3 = QtWidgets.QLabel(self.operatorFrame)
        self.operatorSelectorLabel_3.setEnabled(True)
    #    self.operatorSelectorLabel_3.setGeometry(QtCore.QRect(60, 280, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.operatorSelectorLabel_3.setFont(font)
        self.operatorSelectorLabel_3.setObjectName("operatorSelectorLabel_3")
        
        self.logSelectcomboBox1 = QtWidgets.QComboBox(self.operatorFrame)
    #    self.logSelectcomboBox1.setGeometry(QtCore.QRect(420, 160, 221, 31))
        self.logSelectcomboBox1.setObjectName("logSelectcomboBox1")

        self.logSelectcomboBox2 = QtWidgets.QComboBox(self.operatorFrame)
    #    self.logSelectcomboBox2.setGeometry(QtCore.QRect(420, 210, 221, 31))
        self.logSelectcomboBox2.setObjectName("logSelectcomboBox2")

    #    self.logSelectcomboBox1.activated.connect(self.initAttributes1)
    #    self.logSelectcomboBox2.activated.connect(self.initAttributes2)

        self.attrSelectcomboBox1 = QtWidgets.QComboBox(self.operatorFrame)
    #    self.attrSelectcomboBox1.setGeometry(QtCore.QRect(420, 280, 221, 31))
        self.attrSelectcomboBox1.setObjectName("attrSelectcomboBox1")

        self.attrSelectcomboBox2 = QtWidgets.QComboBox(self.operatorFrame)
    #    self.attrSelectcomboBox2.setGeometry(QtCore.QRect(420, 320, 221, 31))
        self.attrSelectcomboBox2.setObjectName("attrSelectcomboBox2")

        self.operatorAddButton = QtWidgets.QPushButton(self.operatorFrame)
    #    self.operatorAddButton.setGeometry(QtCore.QRect(80, 430, 231, 41))
        self.operatorAddButton.setObjectName("operatorAddButton")
    #    self.operatorAddButton.clicked.connect(self.addToLogs)

        self.operatorExportButton = QtWidgets.QPushButton(self.operatorFrame)
    #    self.operatorExportButton.setGeometry(QtCore.QRect(410, 430, 231, 41))
        self.operatorExportButton.setObjectName("operatorExportButton")
    #    self.operatorExportButton.clicked.connect(lambda checked, x="PlaceHolder": self.export(x))

        
        self.operatorSelectorLabel_2 = QtWidgets.QLabel(self.operatorFrame)
        self.operatorSelectorLabel_2.setEnabled(True)
    #    self.operatorSelectorLabel_2.setGeometry(QtCore.QRect(60, 210, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.operatorSelectorLabel_2.setFont(font)
        self.operatorSelectorLabel_2.setObjectName("operatorSelectorLabel_2")

        # add all labels, buttons etc to right layout
        self.innerRightLayout.addWidget(self.operatorTitleLabel, 0, 0, QtCore.Qt.AlignHCenter)
        self.innerRightLayout.addWidget(self.operatorDescriptionLabel, 1, 0)
        self.innerRightLayout.addWidget(self.operatorSelectorLabel_1, 2, 0)
        self.innerRightLayout.addWidget(self.logSelectcomboBox1, 2, 1)
        self.innerRightLayout.addWidget(self.operatorSelectorLabel_2, 3, 0)
        self.innerRightLayout.addWidget(self.logSelectcomboBox2, 3, 1)
        self.innerRightLayout.addWidget(self.operatorSelectorLabel_3, 4, 0)
        self.innerRightLayout.addWidget(self.attrSelectcomboBox1, 4, 1)
        self.innerRightLayout.addWidget(self.attrSelectcomboBox2, 5, 1)
        self.innerRightLayout.addWidget(self.operatorAddButton, 6, 0)
        self.innerRightLayout.addWidget(self.operatorExportButton, 6, 1)

        # button for viewing object relationships
        self.viewObjectRelationsButton = QtWidgets.QPushButton(self.centralwidget)
        self.viewObjectRelationsButton.setObjectName("viewObjectRelationsButton")
        self.gridLayout.addWidget(self.viewObjectRelationsButton, 1, 0, 1, 1)



        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
